name: Deploy GoTogether to EC2

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  APPLICATION_NAME: gotogether-app
  DEPLOYMENT_GROUP: gotogether-production
  S3_BUCKET: gotogether-private

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create deployment package
      run: |
        zip -r deployment.zip . -x "*.git*" ".github/*" "*.md" "node_modules/*" "*/node_modules/*"

    - name: Upload to S3
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        DEPLOYMENT_KEY="deployments/${TIMESTAMP}-${COMMIT_SHA}/deployment.zip"

        echo "Uploading to s3://${{ env.S3_BUCKET }}/${DEPLOYMENT_KEY}"
        aws s3 cp deployment.zip s3://${{ env.S3_BUCKET }}/${DEPLOYMENT_KEY}

        echo "DEPLOYMENT_KEY=$DEPLOYMENT_KEY" >> $GITHUB_ENV

    - name: Create CodeDeploy Deployment
      run: |
        DEPLOYMENT_ID=$(aws deploy create-deployment \
          --application-name ${{ env.APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
          --s3-location bucket=${{ env.S3_BUCKET }},key=${{ env.DEPLOYMENT_KEY }},bundleType=zip \
          --description "Deploy ${GITHUB_SHA:0:7} by ${GITHUB_ACTOR}" \
          --query 'deploymentId' \
          --output text)

        echo "Deployment ID: $DEPLOYMENT_ID"
        echo "S3 Location: s3://${{ env.S3_BUCKET }}/${{ env.DEPLOYMENT_KEY }}"

        # 배포 상태 확인
        aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_ID

    - name: Cleanup old deployments
      if: success()
      run: |
        echo "Cleaning up old deployment files (keeping last 10)..."
        aws s3 ls s3://${{ env.S3_BUCKET }}/deployments/ | \
          sort -r | \
          tail -n +11 | \
          awk '{print $4}' | \
          xargs -I {} aws s3 rm s3://${{ env.S3_BUCKET }}/deployments/{} --recursive || echo "No old deployments to clean"
